name: Maven Execute

on:
  workflow_dispatch:
    inputs:
      duration: 60

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build project with Maven
      run: timeout ${{ github.event.inputs.duration }} mvn compile exec:java -Dexec.mainClass="com.mycompany.streamaggregator.Driver" || true


