name: Maven Execute

on:
 push:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build project with Maven
      run: timeout 1 mvn compile exec:java -Dexec.mainClass="com.mycompany.streamaggregator.Driver" || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi


